version: '3'

services:
  app:
    image: 'docker-spring-boot-mysql:latest'
    build:
      context: .
    container_name: app_mysql
    depends_on:
      - db_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=compose-mysql

    #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  db_mysql:
    image: 'mysql:latest'
    container_name: db_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=password
        - MYSQL_USER=root
        - MYSQL_PASSWORD=password
    ports:
      - 3606:3606